project_id = "clemkvxneggnokmvgmbj"

[functions.crystalroof-proxy]
verify_jwt = false

[functions.hf-proxy]
verify_jwt = false

[functions.generate-recipe-image]
verify_jwt = false

[functions.generate-feature-image]
verify_jwt = false

[functions.scan-food]
verify_jwt = false

[functions.search-uk-foods]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.realtime-voice-coach]
verify_jwt = false

[functions.mkro-coach]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.generate-weekly-report]
verify_jwt = true

[functions.coach-generate-plan]
verify_jwt = true

[functions.coach-today]
verify_jwt = true

[functions.coach-checkin]
verify_jwt = true
