// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clemkvxneggnokmvgmbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZW1rdnhuZWdnbm9rbXZnbWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTE3ODIsImV4cCI6MjA3NDY2Nzc4Mn0.wYsFizNIe8WhpLuip5Bcd3KpxYAn3X4Mmq9AEe3hKk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});